scikit-tda/kepler-mapper

test/test_mapper.py

Tests that show issue #2 is resolved.

test shows that projections in fit_transform works

---

DISCLAIMER.txt
test/test_mapper.py

I think the library has transcended self-study and has become a useful library for mapper.

Fine tuning the wording in the disclaimer

---

.codecov.yml
.travis.yml
README.md

I think this yml file and hook in the travis.yml file should be enough to integrate the code coverage with travis.

Code coverage badges

---

kmapper/kmapper.py
test/test_coverer.py

The dashboard on the visualization did not adjust to specific dims. Would show [0.2,0.3] repeated 100 times instead of [20%,30%].
This is fixed. I haven't been able to figure out a good way to test the visualize method though.

fix multiple dims in visualize and incorrect defaults

---

kmapper/jupyter.py
kmapper/visuals.py
notebooks/KeplerMapper usage in Jupyter Notebook.ipynb
test/test_visuals.py

Increase the test coverage of visual helper functions.

Increase test coverage

---

MANIFEST.in
docs/index.rst
examples/breast-cancer/breast-cancer.html
examples/breast-cancer/breast-cancer.py
examples/horse/horse.py
examples/horse/horse_keplermapper_output.html
setup.py

Minor updates to the examples and the formatting for the Pypi repo.

Examples and Pypi information

---

setup.py

Pypi now renders the readme correctly 💃

increment to get new pypi features working

---

notebooks/Confidence Graphs.ipynb

Adds an example using variational inference as a lens.

add confidence graphs notebook

---

notebooks/self-guessing/readme.MD

Adds prelim research on self-guessing with Mapper.

Add "Self-guessing Mapper" research

---

kmapper/kmapper.py
kmapper/nerve.py
test/test_mapper.py
test/test_nerve.py

- Fixed the returned simplices in the GraphNerve (there shouldn't be higher order simplices and there were missing edges)
- Lots of tests
- Some notes and comments to guide future development.

Fix returned simplicies for #110

---

notebooks/TOR-XGB-TDA.ipynb

This PR adds a notebook with research/tutorial on supervised and unsupervised detection of encrypted Tor traffic, using data from the paper: Characterization of Tor Traffic using Time based Features (Lashkari et al.).

Add Tor Traffic Detection Research/Tutorial

---

notebooks/TOR-XGB-TDA.ipynb

Comparison not too fair by accidentally using different time lags. Will fix soon.

Make note of 5-second lag vs 15-second lag

---

notebooks/TOR-XGB-TDA.ipynb

Science is hard. Apologies for post-edits. Will proofread better next time.

Fix missing code line and outdated description

---

.travis.yml
kmapper/kmapper.py
kmapper/plotlyviz.py
kmapper/visuals.py
test/test_adapters.py
test/test_drawing.py
test/test_mapper.py
test/test_plotly.py
test/test_visuals.py

remove duplicate nodes before creation of nerve

---

kmapper/cover.py
kmapper/kmapper.py
test/cover_test_script.py
test/hack_test.py
test/test_backwards.py
test/test_coverer.py
test/test_mapper.py

* fix how cubical cover overlapping intervals are determined.
* update cover tests: add index col, test variety of settings for
find_entries
* allow values at upper bound because otherwise highest point-val in dataset gets
chopped off (!!)
closes #125

#125 fix intervals

---

docs/about.rst

Hello, I did a data visualization project using Kepler Mapper, it was awarded in the World Data Visualization Prize https://informationisbeautiful.net/2019/winners-of-the-world-data-visualization-prize/ so I think it was a good idea to add it on the About/Uses & Mentions section. Thank you!

Added a project on About/Uses & Mentions section

---

README.md

Update mapper.map n_cubes definition in README.md

---

kmapper/kmapper.py

I tested equivalence with:
```
nodes_copy = nodes.copy()
for key in nodes.keys():
assert nodes[key] == nodes_copy[key]
```
meta information can be added only if the cover is updated to return bin center information.

one loop pass per prediction

---

paper.md

Regarding the choice of an image, I found these in the docs:
* [breast cancer](https://kepler-mapper.scikit-tda.org/examples.html#unsupervised-anomaly-detection)
* [TOR traffic](https://kepler-mapper.scikit-tda.org/notebooks/TOR-XGB-TDA.html#Image-of-output)
* [whatever the output of the newsgroup NLP vis is](https://kepler-mapper.scikit-tda.org/notebooks/KeplerMapper-Newsgroup20-Pipeline.html)
* [lead out strong with a gymnist horse (lol)](https://kepler-mapper.scikit-tda.org/notebooks/self-guessing.html#d-2)
I vote for either the breast cancer one or the TOR traffic one.
And I haven't referenced the figure in the text yet...

Paper edits

---

paper.md

Fixes #147 
openjournals/joss-reviews#1315

Update name and affiliation for Sam Mangham

---

CONTRIBUTORS.md
kmapper/kmapper.py
kmapper/plotlyviz.py
test/test_mapper.py
test/test_plotly.py

I have removed the mutable arguments, I haven't touched the Color_scale argument.

mutable arguments removed

---

.gitignore
kmapper/kmapper.py
tox.ini

See #185 (but doesn't close that issue)

Fix fixed min samples

---

docs/conf.py

Trying to figure out why the readthedocs isn't building correctly.

cleanup docs config

---

kmapper/cover.py
test/test_coverer.py

added contains() method to Cover class.

---

README.md
docs/index.rst

from the readme, link to the docs citation section, to DRY

---

RELEASE.md
kmapper/plotlyviz.py
kmapper/visuals.py
test/test_plotly.py

Fix plotlyviz color values
