scikit-tda/kepler-mapper

- km.py
A cluster was being built for each of the overlapping bins and an edge added each time a bin overlapped. 
In the one dimensional case, this created a single line. 
This fix now builds nodes for each cluster and edges each time clusters share data points as Mapper is defined in the literature.
> track names of clusters, not initial bins

- kmapper/kmapper.py
Overlap percent and number of intervals were not being updated in fit_transform, so HTML output would show zero. This small 2-line PR fixes that. 
Before: 
After:
> Update overlap_perc and nr_cubes in fit_transform.

- kmapper/kmapper.py
If you haven't run fit_transform first, then self.scaler isn't set yet.  
This presets `self.scaler` to `None` so fit_transform doesn't fail.
> preset scaler incase is visualize is run without fit_transform first

- .gitignore
- examples/lion/lion_keplermapper_output.html
- kmapper/kmapper.py
- test/test_mapper.py
Here's a few minor updates. Mostly updates to address issue #20 
* All of the parameters for the visualization are now in the resulting graph dict instead of attached to self. This makes it possible to save the graph, load it, and then visualize it later while retaining the important information.
* I added a flag to visualize so you can return the html without saving a file to disk. This mostly comes in handy for writing unit tests.
* The docstrings have been converted to abiding by [PEP257](https://www.python.org/dev/peps/pep-0257/) style.
> PR for #20: pep8 docstrings, parameters in graph dict instead of on self, suppress file creation flag

- .coveragerc
- .travis.yml
These changes should make it so Travis-CI generates the code coverage report and uploads it to codecov.
> CI modifications to automatically build coverage report every commit

- kmapper/__init__.py
- kmapper/kmapper.py
- kmapper/nerve.py
- test/test_mapper.py
The previous method `_create_links` is now implemented by `.nerve.GraphNerve`, and will return a list of simplices as well as the neighbor graph needed for `links`.
By returning a full simplex list, alternative nerve methods that create the entire Cech complex of the refined pulled back cover will be easier to implement and integrate, and with them integration of homology (persistent or otherwise) will be easier.
> Abstracted out the nerve builder to a separate class

- kmapper/jupyter.py
- notebooks/KeplerMapper usage in Jupyter Notebook.ipynb
This pull request adds Jupyter Notebook support.
```
from kmapper import jupyter
```
Inside a Jupyter notebook will change the jupyter CSS to accommodate inline display of KeplerMapper.
Display can be done by pointing to a local file (`path_html`) or an externally hosted KeplerMapper output.
```
jupyter.display(path_html="http://mlwave.github.io/tda/word2vec-gender-bias.html")
```
> add Jupyter Notebook support

- DEPLOY.md
- MANIFEST.in
- RELEASE.txt
- kmapper/__init__.py
- setup.py
Previously, the `static` and `templates` were not being included in the install.
This issue was brought to our attention by [Kunal Deore](https://twitter.com/kdeore2).
> Include the visualization html, js, and css in the installation

- kmapper/kmapper.py
HDBSCAN will balk if it is given fewer data points than `min_cluster_size`. This fixes that case.
It is possible that other clustering algorithms have an analogous minimum with a different name. Eventually, we should add most, or devise a work around.
> extract min_cluster_size from hdbscan appropriately

- kmapper/visuals.py
Slight modification to `format_mapper_data()` and `_format_tooltip()` in `visuals.py` such that `node_ID` is also shown in the cluster details pane.
> Add node_ID to cluster pane

- kmapper/cover.py
- kmapper/kmapper.py
- test/test_coverer.py
Adds a `CoverBounds` class - works similarly to `Cover` class, but requires extra variable:
`limits: Numpy array (n_dimension, 2)`
`------ The (min,max) desired value for a given dimension`
This allows a cover to be defined where the limits of the cover are user defined, rather than being the minimum/maximum value of the function. Useful to ensure a series of networks are created with identical parameters.
> Implementation of CoverBounds class

- kmapper/kmapper.py
Clustering functions such as `DBSCAN` accept `metric='precomputed'`, which requires a square distance (dissimilarity) matrix. However, the mapper isn't aware when
precomputed matrices are being passed in, so when it slices according to the filter function values and hypercubes, the square-ness is un-squared.
This PR adds a kludgey way to tell the mapper that a precomputed matrix
is being passed in. When set to `True`, the slice will feed a square
matrix to `clusterer.fit()`
> Enable precomputed similarity matrices

- kmapper/kmapper.py
- test/test_mapper.py
add two new unit tests for lens and map: precomputed and distance_matrix
* `distance_matrix` checks that the kmapper correctly creates a distance
matrix before projecting the lens (but only for euclidean for now)
* `precomputed` tests that the map function feeds the correct square cube
information from the X argument if argument `precompute=True` is passed.
Expected to be used in conjunction with cluster function
`metric='precomputed'`, e.g. with DBSCAN
> Unit tests for Allow precomputed

- kmapper/kmapper.py
The documentation of the scaler parameter in the projection function of the kmapper.py file said that the scaling is done **before** the mapping, but in fact, it is done **after** the mapping. I have changed the documentation to represent that.
> Corrected documentation of scaler in the projection function.

- docs/examples.rst
Some of the descriptions say "check the `example/dir` directory for code." Why not just link to the directory? 🙂 
I noticed it when I was going through the website today. 
Nice work, btw! 👍
- 🔗 it links directly to the github rep, since these examples code doesn't live anywhere in the docs. If those change, then these links will break
- 🙃 I didn't build the website after the change since; I figured y'all will be making changes soon anyway
- 🍔 it breaks the `preformatted styling`... I haven't used .rst before, and I had to run to dinner, so I just went with this
Let me know if you have questions, or if this isn't what you're looking for
> added links to docs/examples.rst

- paper.md
The formatting for this is a bit odd but `![caption here](file.png)`
openjournals/joss-reviews#1315
> Fix figure caption formatting for JOSS paper

- kmapper/kmapper.py
- test/test_mapper.py
As discussed in #162, here is how I made keppler-mapper sparse-compatible with my use case.
> added a sparse-compatible ID column prefixing

- README.md
The zenodo record service provides a DOI that will always resolve to the most recent version of kepler-mapper released there. It's a handy replacement so that the "cite" info in the readme does not need to constantly be updated along with new releases. Might be good to do before JOSS pub.
> Update DOI in readme to project-wide one

- .zenodo.json
This file will give a nice starting point for releases auto-published to zenodo through the github release webhook. I specified the same author info (order, ORCIDs and affiliations) and keywords as in paper.md, and I specified the MIT license from the LICENSE file. 
By default, zenodo reads repo api metadata for the above info, but it can be pretty wrong, as is the current case with kepler-mapper releases on zenodo where it is listed that pep8speaks is a coauthor (lol).
All of this metadata can be edited after the record and DOI are created on zenodo via the github release webhook. So, with this json file in place, it will be easier to prep the zenodo release for JOSS.
I validated the .zenodo.json file using a test repo. Unfortunately, there is no validation method for the .zenodo.json …
> add zenodo json file for easier github release webhook integration

- kmapper/kmapper.py
The purpose of this PR is to add a minor rewrite of minimal cluster sampling in order to allow precomputed distance matrices. This fixes crash when using clustering distance treshold, which is without a fixed number of clusters.
Also a minor rewrite of the print statement. By not specifying type of `min_cluster_samples` it will not crash if a float is passed.
> Enable using precomputed distance matrices for clustering.

- kmapper/kmapper.py
- kmapper/visuals.py
Allows the user to pass in a custom colorscale. 
Sorry for the whitespace change noise. I don't have strong opinions about this stuff, but my editor has its settings. I can submit a different PR w/o these whitespace changes if it helps. I'll put comments on the changes relevant to colorscale.
In some places I used `colorscale=colorscale_default` in function signatures instead of None. If the mutable default is a problem I can either change back to None and put the `if colorscale is None` logic in each function OR write a function in visuals called `_return_default_colorscale` and call that function as the kwarg default value ... so  `colorscale=_return_default_colorscale()` instead of `colorscale=None`.
> allow custom colorscale in KepplerMapper.visualize

- .zenodo.json
- README.md
- docs/index.rst
also updates "how to cite" to the readthedocs to include zenodo and JOSS
> Update citations to v1.4.1

- RELEASE.md
- kmapper/kmapper.py
- test/test_mapper.py
> fix: min_cluster_samples must be an int

- RELEASE.md
- kmapper/kmapper.py
- kmapper/static/kmapper.js
- kmapper/templates/toolbar.html
- The AND and OR searchbar queries no longer multiplies the base size of a node by the ratio of how many of its items match. Rather, the base size of the node is simply multiplied by how many of its items match the query. With this change, the size of a node during an AND or OR search query again directly reflects the number of items within the node.
- The default search mode is now AND (used to be OR) -- because AND is the user-expected behavior, because that's how the google works
> Fix search mode and size

- README.md
- kmapper/plotlyviz.py
- setup.py
As raised in #249, `python-igraph` is deprecated and `igraph` is the drop-in replacement. This PR replaces `python-igraph` with `igraph`.
Closes #249
> Switch python-igraph to igraph
